'''Relevante data om feltene i Enhetsregisteret,
blant annet datatyper'''

kolonner = {'organisasjonsnummer': 'string',
'navn': 'string',
'organisasjonsform.kode': 'category',
'organisasjonsform.beskrivelse': 'category',
'naeringskode1.kode': 'category',
'naeringskode1.beskrivelse': 'category',
'naeringskode2.kode': 'category',
'naeringskode2.beskrivelse': 'category',
'naeringskode2.hjelpeenhetskode': 'string',
'naeringskode3.kode': 'category',
'naeringskode3.beskrivelse': 'category',
'naeringskode3.hjelpeenhetskode': 'string',
'antallAnsatte': 'int',
'hjemmeside': 'string',
'postadresse.adresse': 'string',
'postadresse.poststed': 'category',
'postadresse.postnummer': 'category',
'postadresse.kommune': 'category',
'postadresse.kommunenummer': 'category',
'postadresse.land': 'category',
'postadresse.landkode': 'category',
'forretningsadresse.adresse': 'string',
'forretningsadresse.poststed': 'category',
'forretningsadresse.postnummer': 'category',
'forretningsadresse.kommune': 'category',
'forretningsadresse.kommunenummer': 'category',
'forretningsadresse.land': 'category',
'forretningsadresse.landkode': 'category',
'institusjonellSektorkode.kode': 'category',
'institusjonellSektorkode.beskrivelse': 'category',
'sisteInnsendteAarsregnskap': 'int',
'registreringsdatoEnhetsregisteret': 'date',
'stiftelsesdato': 'date',
'frivilligMvaRegistrertBeskrivelser': 'category',
'registrertIMvaregisteret': 'boolean',
'registrertIFrivillighetsregisteret': 'boolean',
'registrertIForetaksregisteret': 'boolean',
'registrertIStiftelsesregisteret': 'boolean',
'konkurs': 'boolean',
'underAvvikling': 'boolean',
'underTvangsavviklingEllerTvangsopplosning': 'boolean',
'overordnetEnhet': 'string',
'maalform': 'category'}

# %%
